# Generated by Django 3.0 on 2025-03-13 00:17

from django.db import migrations

def move_profiles_data(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')
    
    # Create mapping of old to new profiles
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=old_profile.user,
            favorite_city=old_profile.favorite_city
        )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),  # Make sure this refers to your initial migration
        ('oc_lettings_site', '0001_initial'),  # Check the right migration number
    ]

    operations = [
        migrations.RunPython(move_profiles_data),
    ]