# Generated by Django 3.0 on 2025-03-13 00:17

from django.db import migrations

def move_lettings_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    NewAddress = apps.get_model('lettings', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewLetting = apps.get_model('lettings', 'Letting')

    # Mapping to keep track of old address IDs to new address objects
    address_map = {}

    # Move addresses first
    for old_address in OldAddress.objects.all():
        new_address = NewAddress.objects.create(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
        address_map[old_address.id] = new_address

    # Now move lettings
    for old_letting in OldLetting.objects.all():
        NewLetting.objects.create(
            title=old_letting.title,
            address=address_map[old_letting.address.id]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(move_lettings_data),
    ]
